version: "3"

services:
  web:
    build: .
    ports:
      - "8080"
#    depends_on:
#      - mongo
#    environment:
#      - PORT=8080
    restart: always
  nginx:
    image: nginx:1.17
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    restart: always
